### ISSUE TITLE
KeyError: 'DOWNSAMPLE'

### ISSUE THREAD

**Issue by littlejerry411** [Jarr0d/Human-Parsing-Network#1]
when I run python tools/test.py --cfg experiments/cuhkpedes/seg_hrnet_w48_512x384_sgd_lr7e-3_wd5e-4_bs_40_epoch150.yaml
, it raise "ModuleNotFoundError: No module named 'datasets.cuhkpedes'".Therefore, I find that there is no cuhkpedes.py in Human-Parsing-Network-human/lib/datasets. I add cuhkpedes.py according to cuhk03.py by myself. When this problem is solved, another problem follows：
Traceback (most recent call last):
  File "tools/test.py", line 140, in <module>
    main()
  File "tools/test.py", line 66, in main
    '.get_seg_model')(config)
  File ".../person_reid/Human-Parsing-Network-human/Human-Parsing-Network-human/../lib/models/seg_hrnet.py", line 489, in get_seg_model
    model = HighResolutionNet(cfg, **kwargs)
  File ".../person_reid/Human-Parsing-Network-human/Human-Parsing-Network-human/../lib/models/seg_hrnet.py", line 282, in __init__
    downsample = self.stage2_cfg['DOWNSAMPLE']
KeyError: 'DOWNSAMPLE'
How to solve this problem?

**Comment by Jarr0d** [comment]
Sry we forget to modify the code for cuhk-pedes. We have fix the bug now.

**Comment by littlejerry411** [comment]
Thank you very much!
